### ISSUE TITLE
Video display in Readme.MD

### ISSUE THREAD

**Issue by Smurfgalway** [Smurfgalway/Final-Year-Project-Applied-Diss#2]
Been having trouble getting a youtube video running in the readme file on the git repo home page. This will require more research but I hope to get it finished by the end of the week.

**Comment by DonalMcGahon** [comment]
#### I was able to find a way of displaying an image as an image link for the video that will direct any viewer of our Github repository to the video on YouTube. It does not seem to be possible to embed a YouTube video in the Github markdown file. Here is a [reference](https://stackoverflow.com/questions/11804820/embed-a-youtube-video) as to where I found this information.

**Comment by ConorTighe1995** [comment]
Nice one
